  a <- read.csv("image_stats-blog_flickr_net_en")
  sink("summary-image-blog_flickr_net_en")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-blog_flickr_net_en")
  sink("summary-html-blog_flickr_net_en")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-blog_flickr_net_en")
  sink("summary-javascript-blog_flickr_net_en")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-blog_flickr_net_en")
  sink("summary-css-blog_flickr_net_en")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-blog_flickr_net_en", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-en_wikipedia_org_wiki_Main_Page")
  sink("summary-image-en_wikipedia_org_wiki_Main_Page")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-en_wikipedia_org_wiki_Main_Page")
  sink("summary-html-en_wikipedia_org_wiki_Main_Page")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-en_wikipedia_org_wiki_Main_Page")
  sink("summary-javascript-en_wikipedia_org_wiki_Main_Page")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-en_wikipedia_org_wiki_Main_Page")
  sink("summary-css-en_wikipedia_org_wiki_Main_Page")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-en_wikipedia_org_wiki_Main_Page", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_amazon_com_")
  sink("summary-image-www_amazon_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_amazon_com_")
  sink("summary-html-www_amazon_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_amazon_com_")
  sink("summary-javascript-www_amazon_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_amazon_com_")
  sink("summary-css-www_amazon_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_amazon_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_bbc_co_uk_news")
  sink("summary-image-www_bbc_co_uk_news")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_bbc_co_uk_news")
  sink("summary-html-www_bbc_co_uk_news")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_bbc_co_uk_news")
  sink("summary-javascript-www_bbc_co_uk_news")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_bbc_co_uk_news")
  sink("summary-css-www_bbc_co_uk_news")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_bbc_co_uk_news", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_ebay_com_")
  sink("summary-image-www_ebay_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_ebay_com_")
  sink("summary-html-www_ebay_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_ebay_com_")
  sink("summary-javascript-www_ebay_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_ebay_com_")
  sink("summary-css-www_ebay_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_ebay_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_google_com_")
  sink("summary-image-www_google_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_google_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_google_com_")
  sink("summary-html-www_google_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_google_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_google_com_")
  sink("summary-javascript-www_google_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_google_com_", row.names=F, col.names=F, sep='\t')

      write.table(data_out, file="css-starttime_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_google_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_google_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_imdb_com_")
  sink("summary-image-www_imdb_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_imdb_com_")
  sink("summary-html-www_imdb_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_imdb_com_")
  sink("summary-javascript-www_imdb_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_imdb_com_")
  sink("summary-css-www_imdb_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_imdb_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_npr_org_")
  sink("summary-image-www_npr_org_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_npr_org_")
  sink("summary-html-www_npr_org_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_npr_org_")
  sink("summary-javascript-www_npr_org_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_npr_org_")
  sink("summary-css-www_npr_org_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_npr_org_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_yle_fi_")
  sink("summary-image-www_yle_fi_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_yle_fi_")
  sink("summary-html-www_yle_fi_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_yle_fi_")
  sink("summary-javascript-www_yle_fi_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_yle_fi_")
  sink("summary-css-www_yle_fi_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_yle_fi_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("image_stats-www_youtube_com_")
  sink("summary-image-www_youtube_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-starttime_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-duration_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-size_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="image-total_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("html_stats-www_youtube_com_")
  sink("summary-html-www_youtube_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-starttime_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-duration_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-size_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="html-total_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("javascript_stats-www_youtube_com_")
  sink("summary-javascript-www_youtube_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-starttime_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-duration_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-size_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="javascript-total_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')

  a <- read.csv("css_stats-www_youtube_com_")
  sink("summary-css-www_youtube_com_")
  summary(a)
  sink()
      s_hist <- hist(a$starttime, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-starttime_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$duration, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-duration_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$size, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-size_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')
      s_hist <- hist(a$total, breaks=200)
      data_out <- cbind(s_hist$breaks[-length(s_hist$breaks)],s_hist$counts)
      write.table(data_out, file="css-total_hist-www_youtube_com_", row.names=F, col.names=F, sep='\t')

